# Generated by Django 4.2.5 on 2023-09-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
